# Automatically generated by configure - do not modify
SRC_PATH=/home/grogers1/patch_panel/git_repo/virtual-patch-panel/qemu-2.3.0/roms/seabios
AS=as
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
